# 30/11/2023
#Eleanor Sanderson

#code to make plot of the ols bias against iv bias for the simulation results
#calls the simulation results generated by "ols_2sls_bias.R" (separated to avoid rerunning the sims unnecessarily)


##notes:
#bias_iv is the relative size of the pleitropic effect of Z to the effect of Z on X

library(dplyr)
library(ggplot2)

load("relativebias_sim_results.rda")

graph_res <- results_all %>% 
  group_by(bias_iv) %>% 
  summarise(across(c(wald, tsls_b, ols_b), mean))

graph_res$ols_bias <- graph_res$ols_b - 0.4
graph_res$tsls_bias <- graph_res$tsls_b - 0.4
graph_res$wald_bias <- graph_res$wald - 0.4

ggplot(data = graph_res, aes(x=bias_iv)) +
  geom_line(aes(y = ols_bias, colour="Linear regression")) +
  geom_line(aes(y = tsls_bias, colour="IV")) +
  scale_color_brewer(palette="Set1") +
  labs(x = "Relative pleiotropic effect", y = "Bias", colour="Estimator") +
  theme_bw() +
  theme(legend.position = "bottom")


